# Use a shell executor (assuming it's already configured)

stages:
  - install
  - build
  - deploy

# Install dependencies
install:
  stage: install
  script:
    - apk update && apk add --no-cache nodejs npm
    - npm install

# Build the project
build:
  stage: build
  script:
    - npm run build

# Deploy artifacts to remote server (using SSH key recommended)
deploy:
  stage: deploy
  script:
    - scp -o StrictHostKeyChecking=no -i /path/to/your/ssh/key ./out/* root@77.37.120.17:/var/www/service-charge # Deploy using SSH key

# Define artifacts to upload (prevents specifying path in scp)
artifacts:
  paths:
    - ./out
