import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'lol',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col`}>
        <Header />
        <div className="mb-auto">{children}</div>

        <footer className="mt-7 border-t-2 border-gray-200 p-1 bg-dark">
          <div className="text-center text-white text-sm mb-5 mt-5">
            service-charge.co.uk © {new Date().getFullYear()}
          </div>
        </footer>
      </body>
      <script
        type="text/javascript"
        src="https://www.bing.com/api/maps/mapcontrol?key=AvIqs1Qhw9kBu9iM0IJ2jMhBAYoEUqd-AtiTv_aLuNsHHsFxHMJf3-xkxDhNF-ua&callback=loadMapScenario"
        async
        defer
      ></script>
    </html>
  );
}
