name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest # Or your preferred runner

    steps:
      - uses: actions/checkout@v4 # Checkout code from repository

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.2

      - name: Install dependencies
        run: npm install # Or yarn install

      - name: Load environment variables
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env.build  # Create temporary .env file
          echo NEXT_PUBLIC_GOOGLE_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }} >> .env.build
          echo NEXT_PUBLIC_BING_API_KEY=${{ secrets.NEXT_PUBLIC_BING_API_KEY }} >> .env.build
          echo NEXT_PUBLIC_RESEND_API_KEY=${{ secrets.NEXT_PUBLIC_RESEND_API_KEY }} >> .env.build
          dotenv -r .env.build  # Load variables from temporary file

      - name: Build Next.js app
        run: npm run build # Or yarn build

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          script: |
            cd /root/../var/www/service-charge
            git pull
            npm install
            npm run build
            pm2 restart your-pm2-service-name # Replace with your PM2 service name
