name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest # Or your preferred runner

    steps:
      - uses: actions/checkout@v4 # Checkout code from repository

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.2

      - name: Install dependencies
        run: npm install # Or yarn install

      - name: Load environment variables
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env  # Create temporary .env file
          echo NEXT_PUBLIC_GOOGLE_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }} >> .env
          echo NEXT_PUBLIC_BING_API_KEY=${{ secrets.NEXT_PUBLIC_BING_API_KEY }} >> .env
          echo NEXT_PUBLIC_RESEND_API_KEY=${{ secrets.NEXT_PUBLIC_RESEND_API_KEY }} >> .env

      - name: Build Next.js app
        run: npm run build # Or yarn build

      - name: Remove temporary.env file
        run: rm .env

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          command_timeout: 200m
          script: |
            cd ../var/www/service-charge
            echo "1"
            git pull
            echo "2"
            npm install
            echo "3"
            npm run build
            echo "4"
            pm2 restart your-pm2-service-name # Replace with your PM2 service name
            echo "5"
